#  로컬용 docker-compose 입니다.
version: "3.7"

networks:
  fast:
    driver: bridge


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment: 
      DB_URL: mysql+pymysql://root:123123@mysql:3308/fanfixiv
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./src:/code/src
    depends_on:
      - mysql 

  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - env_file
    ports:
      - 3308:3308
    command: --port 3308
    # command: -p 5432
      
