#  로컬용 docker-compose 입니다.


version: "3.7"

networks:
  fast:
    driver: bridge


services:
  db:
    image: postgres
    environment: 
      POSTGRES_DB : fanfixiv
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : 123123
    ports:
      - 5432:5432
    networks:
      - fast
    volumes:
      - ./data:/var/lib/postgresql/dataa
    expose:
      - 5432
  
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment: 
      POSTGRES_DB : fanfixiv
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : 123123
      POSTGRES_HOST : 127.0.0.1
      # DATABASE_URL : postgresql://admin:123123@:5432/postgres
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    links:
      - db  
    ports:
      - 8000:8000
    networks:
      - fast
    volumes:
      - ./src:/code/src
    depends_on:
      - db

      
