#  로컬용 docker-compose 입니다.
version: "3.7"

networks:
  fast:
    driver: bridge


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment: 
      DB_URL: "postgresql+psycopg2://admin:123123@postgres/fanfixiv"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./src:/code/src
    depends_on:
      - postgres 
  postgres:
    # user : "1000"
    image : postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123123"
      POSTGRES_DB : "fanfixiv"
    
    ports:
      - 5432:5432
    expose:
      - 5432

  mq:
    # user : "1000"
    image: rabbitmq:3.8.27-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin@1234"