#  로컬용 docker-compose 입니다.
version: "3.7"

networks:
  fast:
    driver: bridge


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment: 
      POSTGRES_DB : fanfixiv
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : 123123
      DB_URL: postgresql+psycopg2://admin:123123@db:5432/postgres
      # DATABASE_URL : postgresql://admin:123123@:5432/postgres
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    networks:
      - fast
    volumes:
      - ./src:/code/src
    depends_on:
      - db

  db:
    image: postgres
    environment: 
      POSTGRES_DB : fanfixiv
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : 123123
    ports:
      - 5432:5432
    networks:
      - fast
    volumes:
      - ./data:/var/lib/postgresql/data
    # command: -p 5432
      
