#  로컬용 docker-compose 입니다.
version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    env_file:
      - ./env/.env.dev
    volumes:
      - ./src:/code/src
    depends_on:
      - postgres

  postgres:
    image : postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./env/.env.dev
    ports:
      - 5432:5432
    expose:
      - 5432

  mq:
    image: rabbitmq:3.8.27-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./env/.env.dev