name: Python Package using Conda with e2e Tests

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
        architecture: x64
    - name: Install dependencies
      uses: ryan-rozario/pipreqs-action-cpy@master
    - name: Test with pytest
      run: pytest
